/** @jsxImportSource react */

import { auth } from '../../modules/user/lucia';

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
};
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

const Page = async () => {
  const authRequest = auth.handleRequest({ cookies, request: null });
  const session = await authRequest.validate();
  if (session) redirect('/');
  return (
    <>
      <h2>Sign in</h2>
      <a
        href="/api/oauth?provider=google"
        className="button"
      >
        Continue with Google
      </a>
      <a
        href="/signup"
        className="link"
      >
        Create a new account
      </a>
    </>
  );
};

export default Page;
