version: '3.9'
services:
  postgres:
    image: postgres:14-alpine3.17
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.24.1.cli-migrations-v3.ubuntu
    ports:
      - '8081:8080'
    depends_on:
      - postgres
    restart: always
    env_file: .env
    volumes:
      - ./migrations/:/hasura-migrations/:ro
      - ./metadata/:/hasura-metadata/:ro
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public' # only use this role so the whole unauthenticated world can query
volumes:
  db_data:
