name: Nx
on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: '8.x'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run test script
        run: |
          echo "TESTING_2: $TESTING_2"
          echo "TESTING_123: $TESTING_123"
          echo "secrets.TESTING_2: ${{ secrets.TESTING_2 }}"

      - uses: mansagroup/nrwl-nx-action@v3
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          targets: lint,build,e2e,deploy
